spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8080

# URL del microservicio de datos (Etapa 1 debe estar levantado en 8081)
data:
  service:
    url: http://localhost:8081

# Feign/HTTP timeouts y logging
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: basic
logging:
  level:
    com.TP_6.Sistema_Microservicios.business_service.client: DEBUG
